spring.application.name=backend

# JPA / Hibernate Configuration
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Oauth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,repo

jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

# GitHub Webhook Configuration
github.webhook.secret=${GITHUB_WEBHOOK_SECRET:}
app.base-url=${APP_BASE_URL:http://localhost:8080}