spring.application.name=backend

# Keys JWT
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

# JPA / Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

